
name=notion-connector
connector.class=com.octoby.kafka.notion.source.NotionSourceConnector
tasks.max=1

source.notion.token=${NOTION_API_TOKEN}
source.notion.db.list=${NOTION_DB_LIST}
source.poll.schedule=0 * * * * *
source.topic=NOTION_TEST
